version: 1
formatters:
  simpleFormatter:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simpleFormatter
    stream: ext://sys.stdout

  fileHandler:
    class: logging.FileHandler
    level: INFO
    formatter: simpleFormatter
    filename: logs/app.log
    mode: a

loggers:
  root:
    level: DEBUG
    handlers: [consoleHandler, fileHandler]